site_name: Arko Dapp Migration Guide
theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
    - toc:
        permalink: ïƒ
nav:
  - Home: index.md
  - Block Structure: block_structure.md
  - Transactions: transactions.md
  - Block Service: block_service.md
  - Lamden Vault API: lamden_vault_api.md

